<?php
    if (!defined('ABSPATH')) exit;

    function megamenu_add_theme_hoster___rd7_1553849219($themes)
{
    $themes["hoster___rd7_1553849219"] = array(
        'title' => 'Hoster _ RD7',
        'container_background_from' => 'rgb(255, 255, 255)',
        'container_background_to' => 'rgb(255, 255, 255)',
        'menu_item_align' => 'right',
        'menu_item_background_hover_from' => 'rgb(16, 123, 255)',
        'menu_item_background_hover_to' => 'rgb(16, 123, 255)',
        'menu_item_link_font_size' => '16px',
        'menu_item_link_height' => '69px',
        'menu_item_link_color' => 'rgb(16, 123, 255)',
        'menu_item_link_weight' => 'inherit',
        'menu_item_link_text_align' => 'right',
        'menu_item_link_weight_hover' => 'inherit',
        'menu_item_highlight_current' => 'off',
        'panel_background_from' => 'rgba(255, 255, 255, 0.95)',
        'panel_background_to' => 'rgba(255, 255, 255, 0.95)',
        'panel_header_border_color' => '#555',
        'panel_font_size' => '14px',
        'panel_font_color' => '#666',
        'panel_font_family' => 'inherit',
        'panel_second_level_font_color' => '#555',
        'panel_second_level_font_color_hover' => '#555',
        'panel_second_level_text_transform' => 'uppercase',
        'panel_second_level_font' => 'inherit',
        'panel_second_level_font_size' => '16px',
        'panel_second_level_font_weight' => 'bold',
        'panel_second_level_font_weight_hover' => 'bold',
        'panel_second_level_text_decoration' => 'none',
        'panel_second_level_text_decoration_hover' => 'none',
        'panel_second_level_border_color' => '#555',
        'panel_third_level_font_color' => '#666',
        'panel_third_level_font_color_hover' => '#666',
        'panel_third_level_font' => 'inherit',
        'panel_third_level_font_size' => '14px',
        'flyout_menu_background_from' => 'rgba(255, 255, 255, 0.95)',
        'flyout_menu_background_to' => 'rgba(255, 255, 255, 0.95)',
        'flyout_border_color' => 'rgb(255, 255, 255)',
        'flyout_border_left' => '0',
        'flyout_border_right' => '0',
        'flyout_border_top' => '0',
        'flyout_border_bottom' => '0',
        'flyout_menu_item_divider' => 'on',
        'flyout_link_padding_top' => '10px',
        'flyout_link_padding_bottom' => '10px',
        'flyout_link_weight' => 'inherit',
        'flyout_link_weight_hover' => 'inherit',
        'flyout_link_height' => '30px',
        'flyout_background_from' => 'rgba(255, 255, 255, 0.95)',
        'flyout_background_to' => 'rgba(255, 255, 255, 0.95)',
        'flyout_background_hover_from' => 'rgb(16, 123, 255)',
        'flyout_background_hover_to' => 'rgb(16, 123, 255)',
        'flyout_link_size' => '14px',
        'flyout_link_color' => 'rgb(16, 123, 255)',
        'flyout_link_color_hover' => 'rgb(255, 255, 255)',
        'flyout_link_family' => 'inherit',
        'responsive_breakpoint' => '992px',
        'line_height' => '2',
        'shadow' => 'on',
        'mobile_columns' => '1',
        'toggle_background_from' => 'rgba(34, 34, 34, 0)',
        'toggle_background_to' => 'rgba(34, 34, 34, 0)',
        'mobile_menu_force_width' => 'on',
        'mobile_background_from' => 'rgb(255, 255, 255)',
        'mobile_background_to' => 'rgb(255, 255, 255)',
        'mobile_menu_item_link_font_size' => '14px',
        'mobile_menu_item_link_color' => 'rgb(16, 123, 255)',
        'mobile_menu_item_link_text_align' => 'right',
        'mobile_menu_item_link_color_hover' => 'rgb(16, 123, 255)',
        'mobile_menu_item_background_hover_from' => 'rgb(255, 255, 255)',
        'mobile_menu_item_background_hover_to' => 'rgb(255, 255, 255)',
        'custom_css' => '/** Push menu onto new line **/ 
#{$wrap} { 
    clear: both; 
}',
    );
    return $themes;
}

add_filter("megamenu_themes", "megamenu_add_theme_hoster___rd7_1553849219");